# Generated by Django 5.1.1 on 2024-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_time",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_datetime",
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
