# Generated by Django 5.1.1 on 2024-10-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default="2024-10-23"),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(),
        ),
    ]
