# Generated by Django 5.1.1 on 2024-10-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_booking_booking_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_hour",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_hour",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
