# Generated by Django 5.1.1 on 2024-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_booking_booking_date_alter_room_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.TimeField(default="13:00"),
        ),
    ]
